export const RplIconNames = [
  /* custom */
  "icon-accessible",
  "icon-add",
  "icon-arrow-down",
  "icon-arrow-left",
  "icon-arrow-right",
  "icon-arrow-up",
  "icon-attach",
  "icon-browser",
  "icon-calendar-lined",
  "icon-cancel-circle-filled",
  "icon-car",
  "icon-check",
  "icon-child-lined",
  "icon-dollar-circle-filled",
  "icon-fire",
  "icon-flood",
  "icon-free",
  "icon-instagram",
  "icon-lightning",
  "icon-link",
  "icon-list",
  "icon-loading",
  "icon-log-in-lined",
  "icon-mail-lined",
  "icon-medical",
  "icon-menu",
  "icon-microphone",
  "icon-pause-circle-lined",
  "icon-person",
  "icon-play-circle-lined",
  "icon-print-lined",
  "icon-question-circle-lined",
  "icon-search",
  "icon-senior",
  "icon-share",
  "icon-smoke",
  "icon-spotify",
  "icon-star",
  "icon-stop-circle-lined",
  "icon-table-lined",
  "icon-temperature",
  "icon-traffic",
  "icon-trash-lined",
  "icon-upload",
  "icon-user-circle-filled",
  "icon-video",
  "icon-wechat",
  "icon-youtube",
  "icon-zoom-in",
  "icon-zoom-out",
  /* core */
  "icon-cancel",
  "icon-check-circle-filled",
  "icon-chevron-down",
  "icon-chevron-left",
  "icon-chevron-right",
  "icon-chevron-up",
  "icon-current-location",
  "icon-document-lined",
  "icon-document",
  "icon-download",
  "icon-enlarge-square-filled",
  "icon-enlarge",
  "icon-exclamation-circle-filled",
  "icon-facebook",
  "icon-home",
  "icon-information-circle-filled",
  "icon-link-external-square-filled",
  "icon-linkedin",
  "icon-mail",
  "icon-phone",
  "icon-pin",
  "icon-twitter",
  "icon-view",
  "icon-x"
];

/* move icon constants to ui-core-constants */

export const RplIconGroups = {
  alert: [
    "icon-fire",
    "icon-flood",
    "icon-lightning",
    "icon-medical",
    "icon-smoke",
    "icon-temperature",
    "icon-traffic"
  ],
  social: [
    "icon-facebook",
    "icon-instagram",
    "icon-linkedin",
    "icon-spotify",
    "icon-wechat",
    "icon-youtube",
    "icon-x"
  ],
  standard: [
    "icon-accessible",
    "icon-add",
    "icon-arrow-up",
    "icon-arrow-right",
    "icon-arrow-down",
    "icon-arrow-left",
    "icon-attach",
    "icon-browser",
    "icon-calendar-lined",
    "icon-cancel",
    "icon-cancel-circle-filled",
    "icon-car",
    "icon-check",
    "icon-check-circle-filled",
    "icon-chevron-up",
    "icon-chevron-right",
    "icon-chevron-down",
    "icon-chevron-left",
    "icon-child-lined",
    "icon-current-location",
    "icon-document",
    "icon-document-lined",
    "icon-dollar-circle-filled",
    "icon-download",
    "icon-enlarge",
    "icon-enlarge-square-filled",
    "icon-exclamation-circle-filled",
    "icon-free",
    "icon-home",
    "icon-information-circle-filled",
    "icon-link",
    "icon-link-external-square-filled",
    "icon-list",
    "icon-loading",
    "icon-log-in-lined",
    "icon-mail",
    "icon-mail-lined",
    "icon-menu",
    "icon-microphone",
    "icon-pause-circle-lined",
    "icon-person",
    "icon-phone",
    "icon-pin",
    "icon-play-circle-lined",
    "icon-print-lined",
    "icon-question-circle-lined",
    "icon-search",
    "icon-senior",
    "icon-share",
    "icon-star",
    "icon-stop-circle-lined",
    "icon-table-lined",
    "icon-trash-lined",
    "icon-upload",
    "icon-user-circle-filled",
    "icon-video",
    "icon-view",
    "icon-zoom-in",
    "icon-zoom-out"
  ]
};

export const RplIconSizes = {
  xs: "Extra-small",
  s: "Small",
  m: "Medium",
  l: "Large"
};

export const RplIconPlacement = {
  before: "Before",
  after: "After"
};
