let fs = require("fs").promises;
let path = require("path");
const postcss = require("postcss");
const postcssCustomMedia = require("postcss-custom-media");
let sass = require("sass");
const fileRegEx = /!/;

function genFile(filename) {
  return sass.compile(filename, {
    style: "compressed",
    loadPaths: ["./", "node_modules", "node_modules/@gouvfr/dsfr"]
  });
}

async function* walk(dir) {
  for await (const d of await fs.opendir(dir)) {
    const entry = path.join(dir, d.name);
    if (d.isDirectory()) yield* walk(entry);
    else if (d.isFile() && d.name === ".cssgen.json") yield entry;
  }
}

async function main() {
  for await (const p of walk(".")) {
    console.log(`handling ${p}`);

    fs.readFile(p)
      .then(async (data) => {
        let dot = path.dirname(p);
        let config = JSON.parse(data);

        console.log(`dot ${dot}`);

        for (const directory in config) {
          console.log(`Looking at directory ${directory}`);
          let hasStar = directory.endsWith("*");
          let file = hasStar ? directory.slice(0, -1) : directory; // scss and css file will be name just like their containing folder
          let fileInDirectory = directory.indexOf("/") >= 0;

          const targetDir = fileInDirectory ? dot : dot + "/" + directory;
          const targetFile = `${targetDir}/${file}.scss`;

          let content = genFile(targetFile).css;

          /* go through configured content replacements */

          for (const replacement of config[directory]) {
            let regexFrom = new RegExp(replacement.from, "gm");
            content = content.replaceAll(regexFrom, replacement.to);
          }

          /* use postcss to remove custom media generated by VIC2 */

          postcss([postcssCustomMedia()])
            .process(content)
            .then((pContent) => {
              fs.writeFile(
                fileInDirectory
                  ? `${dot}/${file}${hasStar ? "" : ".gen"}.css`
                  : `${dot}/${directory}/${file}${hasStar ? "" : ".gen"}.css`,
                pContent.css,
                (err) => {
                  if (err) throw err;
                }
              );
            });
        }
      })
      .catch((err) => {
        console.log(err);
        process.exit(1);
      });
  }
}

main();
