import { createElement } from "lwc";
import SfGpsDsUkGovHeroBanner from "c/SfGpsDsUkGovHeroBanner";

const tag = "c-sf-gps-ds-uk-gov-hero-banner";

describe("c-sf-gps-ds-uk-gov-hero-banner", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement(tag, {
      is: SfGpsDsUkGovHeroBanner
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div);
    expect(1).toBe(1);
  });

  it("is accessbile", async () => {
    const element = createElement(tag, {
      is: SfGpsDsUkGovHeroBanner
    });

    document.body.appendChild(element);

    await expect(element).toBeAccessible();
  });
});
