# Unique name for this workflow
name: Packaging Manual
permissions:
  contents: read

# Definition when the workflow should run
on:
  workflow_dispatch:

# Jobs to be executed
jobs:
  trigger-packaging:
    runs-on: ubuntu-latest
    steps:
      # Check for package changes using git diff
      - name: "Check for package changes"
        id: checkForChanges
        run: |
          hasChanges='true'
          hasChangesSfGpsDs='true'
          hasChangesSfGpsDsAuNsw='true'
          hasChangesSfGpsDsAuNswS='true'
          hasChangesSfGpsDsAuQld='true'
          hasChangesSfGpsDsAuVic='true'
          hasChangesSfGpsDsFrGov='true'
          hasChangesSfGpsDsUkGov='true'
          echo "hasChanges=$hasChanges" >> $GITHUB_OUTPUT
          echo "hasChangesSfGpsDs=$hasChangesSfGpsDs" >> $GITHUB_OUTPUT

      # Trigger packaging workflow if needed
      - name: "Trigger packaging workflow if needed"
        uses: peter-evans/repository-dispatch@v2
        if: ${{ steps.checkForChanges.outputs.hasChanges == 'true' }}
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          event-type: start-packaging
          client-payload: '{ "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "sfGpsDs": "${{ steps.checkForChanges.outputs.hasChangesSfGpsDs }}" }'
