# Unique name for this workflow
name: Packaging on PR

# Workflow starts when receiving custom event sent by CI workflow
on:
  repository_dispatch:
    types: [start-packaging-pr]

# Workflow environment variables
env:
  # Is the PR base branch a prerelease branch
  IS_PRERELEASE: ${{ github.event.client_payload.isPrelease }}

# Jobs to be executed
jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: "Checkout source code"
        uses: actions/checkout@v4

      # Install Volta to enforce proper node and package manager versions
      - name: "Install Volta"
        uses: volta-cli/action@v4

      # Cache node_modules to speed up the process
      - name: "Restore node_modules cache"
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ env.cache-name }}-
            npm-

      # Install Salesforce CLI
      - name: "Install Salesforce CLI latest"
        run: |
          npm install @salesforce/cli --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH

      # Confirm version Salesforce CLI
      - name: "Confirm Salesforce CLI version"
        run: |
          sf --version

      # Install npm dependencies for cssgen
      - name: "Install npm dependencies"
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci --force
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_ACCESS_TOKEN }}

      # Prep
      - name: "Prepare repo"
        run: npm run prep

        # Generate css from scss
      - name: "Automatically generate css"
        run: npm run cssgen

      # Generate JS versions of TS source
      - name: "Automatically generate JS source from TypeScript"
        run: npm run build

      # Generate omnistudio versions of source
      - name: "Automatically generate Omnistudio source"
        run: npm run osfilegen

      # Store secret for dev hub
      - name: "Populate auth file with DEVHUB_SFDX_URL secret"
        shell: bash
        run: |
          echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt
          secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
          if [ $secretFileSize == 1 ]; then
              echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
              exit 1;
          fi

      # Authenticate dev hub
      - name: "Authenticate Dev Hub"
        run: sf auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d

      # Remove auth file
      - name: "Remove auth file"
        run: rm -f ./DEVHUB_SFDX_URL.txt

      # Create package version and extract its id
      - name: "Create package version sfGpsDs"
        id: createPackageVersion-sfGpsDs
        if: ${{ github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          set +e
          json=$(sf package version create --path=sfGpsDs --installation-key-bypass --wait=20 --definition-file=config/project-scratch-def.json --code-coverage --json)
          echo "package version create output:"
          echo $json
          echo "----"
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
          else
              echo "sf package version create failed"
              exit $status
          fi

          json2=$(sf package version report --package $packageVersionId --json)
          status2=$(echo $json2 | jq '.status')
          if [ $status2 == "0" ]; then
            versionNumber=$(echo $json2 | jq -r '.result.Version')
            echo "versionNumber=$versionNumber" >> $GITHUB_OUTPUT
          else
            echo "sf package version report failed"
          fi
          exit $status2

      - name: "Create package version sfGpsDsAuNsw"
        id: createPackageVersion-sfGpsDsAuNsw
        if: ${{ github.event.client_payload.sfGpsDsAuNsw == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          set +e
          npm run aunsw-copy
          json=$(sf package version create --path=sfGpsDsAuNswFull --installation-key-bypass --wait=20 --definition-file=config/project-scratch-def.json --code-coverage --json)
          echo "package version create output:"
          echo $json
          echo "----"
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
          else
              echo "sf package version create failed"
              exit $status
          fi

          json2=$(sf package version report --package $packageVersionId --json)
          status2=$(echo $json2 | jq '.status')
          if [ $status2 == "0" ]; then
            versionNumber=$(echo $json2 | jq -r '.result.Version')
            echo "versionNumber=$versionNumber" >> $GITHUB_OUTPUT
          else
            echo "sf package version report failed"
          fi
          exit $status2

      - name: "Create package version sfGpsDsAuNswS"
        id: createPackageVersion-sfGpsDsAuNswS
        if: ${{ github.event.client_payload.sfGpsDsAuNswS == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          set +e
          npm run aunsws-copy
          json=$(sf package version create --path=sfGpsDsAuNswSFull --installation-key-bypass --wait=20 --definition-file=config/project-scratch-def.json --code-coverage --json)
          echo "package version create output:"
          echo $json
          echo "----"
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
          else
              echo "sf package version create failed"
              exit $status
          fi

          json2=$(sf package version report --package $packageVersionId --json)
          status2=$(echo $json2 | jq '.status')
          if [ $status2 == "0" ]; then
            versionNumber=$(echo $json2 | jq -r '.result.Version')
            echo "versionNumber=$versionNumber" >> $GITHUB_OUTPUT
          else
            echo "sf package version report failed"
          fi
          exit $status2

      - name: "Create package version sfGpsDsAuQld"
        id: createPackageVersion-sfGpsDsAuQld
        if: ${{ github.event.client_payload.sfGpsDsAuQld == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          set +e
          npm run auqld-copy
          json=$(sf package version create --path=sfGpsDsAuQldFull --installation-key-bypass --wait=20 --definition-file=config/project-scratch-def.json --code-coverage --json)
          echo "package version create output:"
          echo $json
          echo "----"
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
          else
              echo "sf package version create failed"
              exit $status
          fi

          json2=$(sf package version report --package $packageVersionId --json)
          status2=$(echo $json2 | jq '.status')
          if [ $status2 == "0" ]; then
            versionNumber=$(echo $json2 | jq -r '.result.Version')
            echo "versionNumber=$versionNumber" >> $GITHUB_OUTPUT
          else
            echo "sf package version report failed"
          fi
          exit $status2

      - name: "Create package version sfGpsDsAuVic2"
        id: createPackageVersion-sfGpsDsAuVic2
        if: ${{ github.event.client_payload.sfGpsDsAuVic2 == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          set +e
          npm run auvic2-copy
          json=$(sf package version create --path=sfGpsDsAuVic2Full --installation-key-bypass --wait=20 --definition-file=config/project-scratch-def.json --code-coverage --json)
          echo "package version create output:"
          echo $json
          echo "----"
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
          else
              echo "sf package version create failed"
              exit $status
          fi

          json2=$(sf package version report --package $packageVersionId --json)
          status2=$(echo $json2 | jq '.status')
          if [ $status2 == "0" ]; then
            versionNumber=$(echo $json2 | jq -r '.result.Version')
            echo "versionNumber=$versionNumber" >> $GITHUB_OUTPUT
          else
            echo "sf package version report failed"
          fi
          exit $status2

      - name: "Create package version sfGpsDsFrGov"
        id: createPackageVersion-sfGpsDsFrGov
        if: ${{ github.event.client_payload.sfGpsDsFrGov == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          set +e
          npm run frgov-copy
          json=$(sf package version create --path=sfGpsDsFrGovFull --installation-key-bypass --wait=20 --definition-file=config/project-scratch-def.json --code-coverage --json)
          echo "package version create output:"
          echo $json
          echo "----"
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
          else
              echo "sf package version create failed"
              exit $status
          fi

          json2=$(sf package version report --package $packageVersionId --json)
          status2=$(echo $json2 | jq '.status')
          if [ $status2 == "0" ]; then
            versionNumber=$(echo $json2 | jq -r '.result.Version')
            echo "versionNumber=$versionNumber" >> $GITHUB_OUTPUT
          else
            echo "sf package version report failed"
          fi
          exit $status2

      - name: "Create package version sfGpsDsUkGov"
        id: createPackageVersion-sfGpsDsUkGov
        if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          set +e
          npm run ukgov-copy
          json=$(sf package version create --path=sfGpsDsUkGovFull --installation-key-bypass --wait=20 --definition-file=config/project-scratch-def.json --code-coverage --json)
          echo "package version create output:"
          echo $json
          echo "----"
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
          else
              echo "sf package version create failed"
              exit $status
          fi

          json2=$(sf package version report --package $packageVersionId --json)
          status2=$(echo $json2 | jq '.status')
          if [ $status2 == "0" ]; then
            versionNumber=$(echo $json2 | jq -r '.result.Version')
            echo "versionNumber=$versionNumber" >> $GITHUB_OUTPUT
          else
            echo "sf package version report failed"
          fi
          exit $status2

      # Wait for package replication
      - name: "Wait for package replication"
        uses: maddox/actions/sleep@master
        with:
          args: 360

      # Create pre-release scratch org
      - name: "Create pre-release scratch org"
        if: ${{ env.IS_PRERELEASE }}
        run: sf org create scratch -f config/project-scratch-def.json --alias=scratch-org --set-default --duration-days=1 --release=preview --no-track-source

        # Create scratch org
      - name: "Create scratch org"
        if: ${{ !env.IS_PRERELEASE }}
        run: sf org create scratch -f config/project-scratch-def.json --alias=scratch-org --set-default --duration-days=1 --no-track-source

      # Deploy omnistudio to scratch org
      - name: "Deploy Omnistudio"
        run: sf package install --package=${{ vars.OMNISTUDIO_PACKAGEID }} --target-org=scratch-org --wait=20 --no-prompt --security-type=AllUsers

      # Install new sfGpsDs package in scratch org
      - name: "Install new sfGpsDs package version in scratch org"
        if: ${{ github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          sf package install --package ${{ steps.createPackageVersion-sfGpsDs.outputs.packageVersionId }} --wait=20 --target-org=scratch-org --no-prompt
          sf package uninstall --package ${{ steps.createPackageVersion-sfGpsDs.outputs.packageVersionId }} --wait=20 --target-org=scratch-org

      # Install new sfGpsDsAuNsw package in scratch org
      - name: "Install new sfGpsDsAuNsw package version in scratch org"
        if: ${{ github.event.client_payload.sfGpsDsAuNsw == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          sf package install --package ${{ steps.createPackageVersion-sfGpsDsAuNsw.outputs.packageVersionId }} --wait=20 --target-org=scratch-org --no-prompt
          sf package uninstall --package ${{ steps.createPackageVersion-sfGpsDsAuNsw.outputs.packageVersionId }} --wait=20 --target-org=scratch-org

      # Install new sfGpsDsAuNswS package in scratch org
      - name: "Install new sfGpsDsAuNswS package version in scratch org"
        if: ${{ github.event.client_payload.sfGpsDsAuNswS == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          sf package install --package ${{ steps.createPackageVersion-sfGpsDsAuNswS.outputs.packageVersionId }} --wait=20 --target-org=scratch-org --no-prompt
          sf package uninstall --package ${{ steps.createPackageVersion-sfGpsDsAuNswS.outputs.packageVersionId }} --wait=20 --target-org=scratch-org

      # Install new sfGpsDsAuQld package in scratch org
      - name: "Install new sfGpsDsAuQld package version in scratch org"
        if: ${{ github.event.client_payload.sfGpsDsAuQld == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          sf package install --package ${{ steps.createPackageVersion-sfGpsDsAuQld.outputs.packageVersionId }} --wait=20 --target-org=scratch-org --no-prompt
          sf package uninstall --package ${{ steps.createPackageVersion-sfGpsDsAuQld.outputs.packageVersionId }} --wait=20 --target-org=scratch-org

      # Install new sfGpsDsAuVic2 package in scratch org
      - name: "Install new sfGpsDsAuVic2 package version in scratch org"
        if: ${{ github.event.client_payload.sfGpsDsAuVic2 == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          sf package install --package ${{ steps.createPackageVersion-sfGpsDsAuVic2.outputs.packageVersionId }} --wait=20 --target-org=scratch-org --no-prompt
          sf package uninstall --package ${{ steps.createPackageVersion-sfGpsDsAuVic2.outputs.packageVersionId }} --wait=20 --target-org=scratch-org

      # Install new sfGpsDsFrGov package in scratch org
      - name: "Install new sfGpsDsFrGov package version in scratch org"
        if: ${{ github.event.client_payload.sfGpsDsFrGov == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          sf package install --package ${{ steps.createPackageVersion-sfGpsDsFrGov.outputs.packageVersionId }} --wait=20 --target-org=scratch-org --no-prompt
          sf package uninstall --package ${{ steps.createPackageVersion-sfGpsDsFrGov.outputs.packageVersionId }} --wait=20 --target-org=scratch-org

      # Install new sfGpsDsUkGov package in scratch org
      - name: "Install new sfGpsDsUkGov package version in scratch org"
        if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          sf package install --package ${{ steps.createPackageVersion-sfGpsDsUkGov.outputs.packageVersionId }} --wait=20 --target-org=scratch-org --no-prompt
          sf package uninstall --package ${{ steps.createPackageVersion-sfGpsDsUkGov.outputs.packageVersionId }} --wait=20 --target-org=scratch-org

      # Housekeeping
      - name: "Delete scratch org"
        if: always()
        run: sf org delete scratch --no-prompt --target-org=scratch-org
