# Unique name for this workflow
name: Packaging on PR

# Workflow starts when receiving custom event sent by CI workflow
on:
  repository_dispatch:
    types: [start-packaging-pr]

# Jobs to be executed
jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: "Checkout source code"
        uses: actions/checkout@v3

      # Install Volta to enforce proper node and package manager versions
      - name: "Install Volta"
        uses: volta-cli/action@v3

      # Cache node_modules to speed up the process
      - name: "Restore node_modules cache"
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ env.cache-name }}-
            npm-

      # Install Salesforce CLI
      - name: "Install Salesforce CLI v7.182.1"
        run: |
          npm install sfdx-cli@7.182.1 --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH

      # Install Salesforce CLI
      - name: "Confirm Salesforce CLI version"
        run: |
          sfdx --version

      # Install npm dependencies for cssgen
      - name: "Install npm dependencies"
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      # Prep
      - name: "Prepare repo"
        run: npm run prep

        # Generate css from scss
      - name: "Automatically generate css"
        run: npm run cssgen

      # Generate omnistudio versions of source
      - name: "Automatically generate Omnistudio source"
        run: npm run osfilegen

      # Copy UkGovFull
      - name: "Copy UkGovFull"
        run: npm run ukgov-copy

      # Store secret for dev hub
      - name: "Populate auth file with DEVHUB_SFDX_URL secret"
        shell: bash
        run: |
          echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt
          secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
          if [ $secretFileSize == 1 ]; then
              echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
              exit 1;
          fi

      # Authenticate dev hub
      - name: "Authenticate Dev Hub"
        run: sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d

      # Remove auth file
      - name: "Remove auth file"
        run: rm -f ./DEVHUB_SFDX_URL.txt

      # Create package version and extract its id
      - name: "Create package version sfGpsDs"
        id: createPackageVersion-sfGpsDs
        if: ${{ github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          set +e
          json=$(sfdx force:package:version:create -d sfGpsDs -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
          echo "force:package:version:create output:"
          echo $json
          echo "----"
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
          else
              echo "sfdx force:package:version:create failed"
          fi
          exit $status

      - name: "Create package version sfGpsDsAuNsw"
        id: createPackageVersion-sfGpsDsAuNsw
        if: ${{ github.event.client_payload.sfGpsDsAuNsw == 'true' }}
        run: |
          set +e
          json=$(sfdx force:package:version:create -d sfGpsDsAuNsw -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
          echo "force:package:version:create output:"
          echo $json
          echo "----"
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
          else
              echo "sfdx force:package:version:create failed"
          fi
          exit $status

      - name: "Create package version sfGpsDsAuNswS"
        id: createPackageVersion-sfGpsDsAuNswS
        if: ${{ github.event.client_payload.sfGpsDsAuNswS == 'true' }}
        run: |
          set +e
          json=$(sfdx force:package:version:create -d sfGpsDsAuNswS -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
          echo "force:package:version:create output:"
          echo $json
          echo "----"
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
          else
              echo "sfdx force:package:version:create failed"
          fi
          exit $status

      - name: "Create package version sfGpsDsAuVic"
        id: createPackageVersion-sfGpsDsAuVic
        if: ${{ github.event.client_payload.sfGpsDsAuVic == 'true' }}
        run: |
          set +e
          json=$(sfdx force:package:version:create -d sfGpsDsAuVic -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
          echo "force:package:version:create output:"
          echo $json
          echo "----"
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
          else
              echo "sfdx force:package:version:create failed"
          fi
          exit $status

      - name: "Create package version sfGpsDsUkGov"
        id: createPackageVersion-sfGpsDsUkGov
        if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' }}
        run: |
          set +e
          json=$(sfdx force:package:version:create -d sfGpsDsUkGov -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
          echo "force:package:version:create output:"
          echo $json
          echo "----"
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
          else
              echo "sfdx force:package:version:create failed"
          fi
          exit $status

      - name: "Create package version sfGpsDsUkGovFull"
        id: createPackageVersion-sfGpsDsUkGovFull
        if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          set +e
          json=$(sfdx force:package:version:create -d sfGpsDsUkGovFull -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
          echo "force:package:version:create output:"
          echo $json
          echo "----"
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
          else
              echo "sfdx force:package:version:create failed"
          fi
          exit $status

      # Wait for package replication
      - name: "Wait for package replication"
        uses: maddox/actions/sleep@master
        with:
          args: 360

      # Create scratch org
      - name: "Create scratch org"
        run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1

      # Deploy omnistudio to scratch org
      - name: "Deploy Omnistudio"
        run: sfdx force:package:install -p ${{ vars.OMNISTUDIO_PACKAGEID }} -u scratch-org -w 20 -r -s=AllUsers

      # Install new sfGpsDs package in scratch org
      - name: "Install new sfGpsDs package version in scratch org"
        if: ${{ github.event.client_payload.sfGpsDs == 'true' }}
        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDs.outputs.packageVersionId }} -w 20 -u scratch-org -r

      # Get current sfGpsDs package version
      - name: "Get current sfGpsDs package version"
        id: currentSfGpsDsPack
        if: ${{ github.event.client_payload.sfGpsDs == 'false' }}
        run: |
          packageVersionId=$(sfdx force:package:version:list -p 'Salesforce Global Public Sector Design Systems' -o CreatedDate --concise | tail -1 | awk '{print $3}')
          echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT

      # Install old sfGpsDs package in scratch org
      - name: "Install current sfGpsDs package version in scratch org"
        if: ${{ github.event.client_payload.sfGpsDs == 'false' }}
        run: sfdx force:package:install -p ${{ steps.currentSfGpsDsPack.outputs.packageVersionId }} -w 20 -u scratch-org -r

      # Install new sfGpsDsAuNsw package in scratch org
      - name: "Install new sfGpsDsAuNsw package version in scratch org"
        if: ${{ github.event.client_payload.sfGpsDsAuNsw == 'true' }}
        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuNsw.outputs.packageVersionId }} -w 20 -u scratch-org -r

      # Install new sfGpsDsAuNswS package in scratch org
      - name: "Install new sfGpsDsAuNswS package version in scratch org"
        if: ${{ github.event.client_payload.sfGpsDsAuNswS == 'true' }}
        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuNswS.outputs.packageVersionId }} -w 20 -u scratch-org -r

      # Install new sfGpsDsAuVic package in scratch org
      - name: "Install new sfGpsDsAuVic package version in scratch org"
        if: ${{ github.event.client_payload.sfGpsDsAuVic == 'true' }}
        run: sfdx force:force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuVic.outputs.packageVersionId }} -w 20 -u scratch-org -r

      # Install new sfGpsDsUkGov package in scratch org
      - name: "Install new sfGpsDsUkGov package version in scratch org"
        if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' }}
        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsUkGov.outputs.packageVersionId }} -w 20 -target-org scratch-org -r

      # Update sfGpsDs force:force:package:install link in readme
      - name: "Update package sfGpsDs install link in readme"
        if: ${{ github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          packageVersionId="${{ steps.createPackageVersion-sfGpsDs.outputs.packageVersionId }}"
          packageLinkRegex="https:\/\/test\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDs\""
          newPackageLink="https://test.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDs\""
          sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md

      # Update sfGpsDsAuNsw force:force:package:install link in readme
      - name: "Update package sfGpsDsAuNsw install link in readme"
        if: ${{ github.event.client_payload.sfGpsDsAuNsw == 'true' }}
        run: |
          packageVersionId="${{ steps.createPackageVersion-sfGpsDsAuNsw.outputs.packageVersionId }}"
          packageLinkRegex="https:\/\/test\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsAuNsw\""
          newPackageLink="https://test.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsAuNsw\""
          sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md

      # Update sfGpsDsAuNswS force:force:package:install link in readme
      - name: "Update package sfGpsDsAuNswS install link in readme"
        if: ${{ github.event.client_payload.sfGpsDsAuNswS == 'true' }}
        run: |
          packageVersionId="${{ steps.createPackageVersion-sfGpsDsAuNswS.outputs.packageVersionId }}"
          packageLinkRegex="https:\/\/test\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsAuNswS\""
          newPackageLink="https://test.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsAuNswS\""
          sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md

      # Update sfGpsDsAuVic force:force:package:install link in readme
      - name: "Update package sfGpsDsAuVic install link in readme"
        if: ${{ github.event.client_payload.sfGpsDsAuVic == 'true' }}
        run: |
          packageVersionId="${{ steps.createPackageVersion-sfGpsDsAuVic.outputs.packageVersionId }}"
          packageLinkRegex="https:\/\/test\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsAuVic\""
          newPackageLink="https://test.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsAuVic\""
          sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md

      # Update sfGpsDsUkGov force:force:package:install link in readme
      - name: "Update package sfGpsDsUkGov install link in readme"
        if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' }}
        run: |
          packageVersionId="${{ steps.createPackageVersion-sfGpsDsUkGov.outputs.packageVersionId }}"
          packageLinkRegex="https:\/\/test\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsUkGov\""
          newPackageLink="https://test.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsUkGov\""
          sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md

      # Update sfGpsDsUkGovFull force:force:package:install link in readme
      - name: "Update package sfGpsDsUkGov install link in readme"
        if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
        run: |
          packageVersionId="${{ steps.createPackageVersion-sfGpsDsUkGovFull.outputs.packageVersionId }}"
          packageLinkRegex="https:\/\/test\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsUkGovFull\""
          newPackageLink="https://test.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsUkGovFull\""
          sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md

      # run prettier as sfdx-package.json gets overwritten in a non-prettier way
      - name: "Run prettier"
        run: |
          npm ci
          npm run prettier

      # Housekeeping
      - name: "Delete scratch org"
        if: always()
        run: sfdx force:org:delete -p -u scratch-org
