name: Greeting
permissions:
  issues: write

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: macos-latest
    steps:
      - uses: rytswd/respost@v0.1.0
        with:
          title: Welcome! 👋
          body: "Thank you for posting this issue. 🙇🏼‍♂️ We will come back to you latest within the next 48h (working days). Stay tuned!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
